### ISSUE TITLE
Pharokka Database Install Failed.

### ISSUE THREAD

**Issue by sujeetpowar** [gbouras13/pharokka#241]
I was installing pharokka but for some reason I can not install the databases with this command: install_databases.py -d
So I manually downloaded the databases from the following link:  https://zenodo.org/record/7563578/files/pharokka_v1.2.0_database.tar.gz(pharokka) But I still can not make it work. Is there any way that I can complete database installation and start using pharokka?
Since I am new to the bioinformatics I am not exactly sure what to do after downloading databases manually. 
Your help is much appreciated.

**Comment by gbouras13** [comment]
Hi Sujeet,

Would you be able to give me some more information about what you tried? Maybe screenshots if that is ok?

Assuming you have put the manually downloaded database in your current directory (it is called pharokka_v1.2.0_databases), you will need to add 

-d pharokka_v1.2.0_databases 

to your pharokka command.

e.g. 

```pharokka.py -i input.fasta -o output -d pharokka_v1.2.0_databases ```

Otherwise, you could specify the full path to wherever the database is:

e.g.

```pharokka.py -i input.fasta -o output -d ~/pharokka_v1.2.0_databases ```

George

**Comment by sujeetpowar** [comment]
Hi George,

Thank you so much for your quick reply. I just realized the mistake I was doing and I tried the solution you mentioned and it worked. I realized the the problem was because of my limited understanding.

Anyway thank you so much for your help.

**Comment by gbouras13** [comment]
No problem Sujeet, I hope you find the output useful.

I was in your shoes not too long ago - the more bioinformatics you do the better you get :)

George
