### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by r4carson** [gbouras13/pharokka#285]
* pharokka version:
* Python version:
* Operating System:

### Description

I was just wondering if the meta -m flag assemble a phage genome or should I assemble the genome first? Does meta -m flag only combine contigs from the consensus sequence?

**Comment by gbouras13** [comment]
Hi @r4carson,

Thanks for the great question!

 Pharokka does not do assembly at all, nor does it combine contigs. All -m does is tell pharokka to expect multiple contigs in the input file, so it can do some things in the background to make it run a lot faster. If you have multiple contigs from a metagenome, definitely use -m, otherwise don’t.

For assembly I’d recommend metaspades, megahit or flye depending on your reads. For the combining of assemblies I’d recommend phables  https://github.com/Vini2/phables.

George

**Comment by gbouras13** [comment]
I'm closing this now @r4carson - any other questions feel free to ask them.
