### ISSUE TITLE
Pharokka fails when contig input file ends in .fa, runs when file ends in .fasta

### ISSUE THREAD

**Issue by nelsonruth11** [gbouras13/pharokka#301]
* pharokka version: 1.3.2
* Python version: 3.10.8
* Operating System: Mac

### Description
When the input file ends in .fa, pharokka fails with the message:

> Traceback (most recent call last):
>   File "/home/my_name/miniconda3/envs/pharokka/bin/pharokka.py", line 3, in <module>
>     import input_commands
>   File "/path_1/path_2/home/my_name/miniconda3/envs/pharokka/bin/input_commands.py", line 5, in <module>
>     from Bio import SeqIO
> ModuleNotFoundError: No module named 'Bio'

When I changed my input file to end in .fasta and nothing else, it ran. Unsure why this would happen, but thought I should report it. I am also running on an hpc if that helps.

Here's the command:
`pharokka.py -i contigs.fa -o $output_dir -d $db -t 14 -m -p contigs`

Thanks for making this tool!
-Nelson

**Comment by gbouras13** [comment]
Hi @nelsonruth11 ,

Thanks for using pharokka and reporting this!

That is very strange - the error you report is because Pharokka can't import biopython, so not sure why the file prefix would affect that. But thanks for reporting in case others run into this issue.

p.s. if you can, I'd recommend upgrading Pharokka to at least v1.4.0 or ideally the latest version if you can (I know it can be hard on HPC), I added HMMs in v1.4.0 and it gives more annotations than earlier versions :)

I'm going to close this issue now as I am pretty sure it's not because of the suffix but because of some system specific thing, but if you come across this again please reopen the issue.

George
